### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by moose241986** [rmotr-curriculum/post-your-question-questions#104]
I Removed a_date = (1987, 9, 29) but i still giving me an error

TypeError: format_date() missing 1 required positional argument: 'a_date'

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python


# your code here (if any)
# Import the library here!
from datetime import date
a_date = (1987, 9, 29)


def format_date(a_date):
    return a_date.strftime("%A, %B %d %Y")
    
print(format_date())
```

**Comment by jsymons** [comment]
So if you look at the method signature for `format_date`:
```python
def format_date(a_date):
```
It's expecting you to pass in a parameter when you call it. ie `format_date(my_date_variable)` where as you're calling it like this: `format_date()` this is why it's giving you the error saying "missing 1 required positional argument"

**Comment by ghost** [comment]
> So if you look at the method signature for `format_date`:
> 
> ```python
> def format_date(a_date):
> ```
> 
> It's expecting you to pass in a parameter when you call it. ie `format_date(my_date_variable)` where as you're calling it like this: `format_date()` this is why it's giving you the error saying "missing 1 required positional argument"

# your code here (if any)
# Import the library here!
from datetime import date
a_date = (1987, 9, 29)


def format_date(a_date):
    return a_date.strftime("%A, %B %d %Y")
    
print(format_date(a_date))

if I plug in the positional argument "a_date " in it gives me AttributeError: 'tuple' object has no attribute 'strftime' I have to be missing a tiny detail. I have always been able to print functions this way. Is there something different about this because it is a module. a_date = (1987, 9, 29) is a tuple that is formatted by the strftime method. When I input the argument  tuple a_date it should print out a correct result. This seems so simple but I feel like I am missing an important point and it's stopping me from solving this problem.

**Comment by jsymons** [comment]
That's because you're passing in a tuple instead of a datetime object.

**Comment by ghost** [comment]
That makes sense. Thank You!!
