### ISSUE TITLE
function returning wrong object type

### ISSUE THREAD

**Issue by selmabensaid** [rmotr-curriculum/post-your-question-questions#132]
when I run the test it seems that my function is not returning a string.

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
@app.route('/user?search=<user>')
def search_user(user):
    """
        Implement a view that receives a '?search=' query parameter in the URL,
        and returns the amount of users in the given users_list that contains
        that search string in their names.
        i.e: /user?search=mo will return 'Found 2 users that match with search "mo"'
    """
    # HINT: to access the query params you'll need to use request.args.get()
    # function imported from flask
    users = ['Jack', 'Morgan', 'Moe', 'Steve']
    count = 0
    for item in users:
        if item in user:
            count+=1
    return 'Found {} users that match with search: "{}"'.format(count, user)

```

**Comment by jsymons** [comment]
You can't specify query parameters (the `?` and everything after it) as part of the route. What's most likely happening is that the test is returning a 404 because it couldn't find a matching route. Your route should instead be `@app.route('/user)` and then inside your function you can get the parameter via `request.args.get('search')` (Make sure you've done a `from flask import request` at the top of your file)
