### ISSUE TITLE
"Get Positions of char"

### ISSUE THREAD

**Issue by topher-allen** [rmotr-curriculum/post-your-question-questions#150]
Hi, I've been trying to understand this lesson in unit 2 for a while now:
https://learn.rmotr.com/python/base-python-track/advanced-control-flow/get-positions-of-char

But I'm still not clear on how to implement the solution. I see in the given code that enumerate is used in a for each loop with 2 elements but am not understanding how it all comes together..?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# your code here (if any)
```

**Comment by martinzugnoni** [comment]
@mrtophalicious the `enumerate` function helps you get the current index of the iteration. For example:

If you have a list of elements and you apply the `enumerate` function to it, you will get a new collection containing 2-elements tuples, where the first element is always the element index and the second the element itself. Like this:

```
>>> a_list = ["eat","sleep","repeat"]
>>> enumerate(a_list)
[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]
```

That's why you are seeing two variables in the for loop structure. The index will be assigned to the first variable, and the element to the second one.

Hope it helps.
