### ISSUE TITLE
substract reversed 

### ISSUE THREAD

**Issue by mohabouh** [rmotr-curriculum/post-your-question-questions#18]
not sure why it fails 

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def subtract_reversed(a_list):
    if a_list == []:
        return 0
    elif len(a_list) == 1:
        return a_list[0]
        
    else:
         i = -1
         sub = a_list [i]
         while i <= abs(len(a_list)):
             sub = sub - a_list[i-1]
             i -=  1
         return sub  
```

**Comment by jsymons** [comment]
A couple of issues.
```python
while i <= abs(len(a_list)):
```
Your code is written such that `i` will *always* be negative, thus this statement will always be `True`, causing an infinite loop (which you're not encountering due to the error I'll talk about next), to fix this your `abs` should be around `i` instead of around `len(a_list)`, `a_list` is always going to have a positive length, you need the positive value of `i` to make the statement work.

```python
sub = sub - a_list[i-1]
```
This is causing your code to get an out of bounds exception on the final iteration, for example on our first test with a list length of 4, on your final iteration `i = -4`, which would make your above code evaluate to `sub = sub - a_list[-5]` which is out of bounds. You either need to adjust your while loop to use `<` instead of `<=` so it iterates one less time or you initialize i with a value of `-2` instead of `-1`and change your sub line to `sub = sub = a_list[i]` and also change `sub = a_list[i]` to `sub = a_list[-1]`.

Let me know if you need any of this clarified.
