### ISSUE TITLE
Multi-Search in Advanced Function unit

### ISSUE THREAD

**Issue by AshutoshAhmadAlexandar** [rmotr-curriculum/post-your-question-questions#33]
What am I doing wrong here?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
# Multi-search question for Advanced Function unit.

def search_animals(list_of_animals, given_name=None, animal_type=None):
    result_list = []
    for animals in list_of_animals:
        if given_name is None or given_name not in animals['given_name']:
            continue
        if animal_type is None or animal_type not in animals['animal_type']:
            continue
        if animal_type is None or animal_type not in animals['street_name']:
            continue
        result_list.append(animals)
    return result_list
    
#What am I doing wrong here?
```

**Comment by jsymons** [comment]
You're getting empty lists because of your `continue` statements, or specifically the if statements triggering them. If `given_name` or `animal_type` is None the `continue` statements **always** trigger for every element, thus meaning 0 results.
Instead of creating a bunch of statements linked to `continue`s it might be simpler to just create if statements to handle when there is a match that should be appended.

**Comment by AshutoshAhmadAlexandar** [comment]
Is there any way to check if the parameters is not None

If parameter is not None:
-Doesn't work.

**Comment by jsymons** [comment]
`if parameter is not None` **should** work
