### ISSUE TITLE
Assignment #3

### ISSUE THREAD

**Issue by mattmm41286** [rmotr-curriculum/post-your-question-questions#46]
Not really sure where to go with this one.  Any suggestions or sections I can refer to in order to figure this one out?  

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
def players_by_country_and_position(squads_list):
    players= {
        "Argentina":{
            "Gk":[],
            "FW":[],
            "MF":[],
            "DF":[]
            
    }}
   
   for player_as_list in squads_list:
        player= transform_list_player_to_dictionary(player_as_list)
        country=player["country"]
        position= player["position"]
        
        players{country.append(player),[position]}
    return players
```

**Comment by jsymons** [comment]
So the code for assignment 3 should be very similar to what you had for assignment 2. Instead of just generating the keys for position in the fly you'll be generating the keys for countries which will have dictionaries associated with them, and then you'll be generating position keys for *those* dictionaries.
