### ISSUE TITLE
Return failing inside of IF Statement

### ISSUE THREAD

**Issue by garybutler288** [rmotr-curriculum/post-your-question-questions#67]
Why does the code I have commented out fail.  I put the IF above the while so I'm guessing it has something to do with that but I'm unclear.
See Code Here:
https://repl.it/@GaryButler1/EquatorialFloweryInterpreter

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python


```

**Comment by jsymons** [comment]
I've copied your code below for reference:
```python
#It's ugly but it works.
#How could this be done in a simplified fashion?


def create_counting_list(count_to_number):
    count = 0
    new_list = [] 
    if count_to_number < 0:
      return 'cannot be negative'
    while count <= count_to_number:
        #if count_to_number < 0:    WHY DOES THIS FAIL TO RETURN NEGATIVE???
         # return 'cannot be negative'
        if count_to_number == 0:
          break
        else:
            new_list.append(count_to_number)
            count_to_number = count_to_number - 1
    return new_list[::-1]
print(create_counting_list(-1))
```
The if inside the loop fails because it's impossible for it to trigger. The while loop states that `count <= count_to_number` since count is initialized to `0`, this means that if `count_to_number` was negative (less than zero) that the while condition would not be met, and thus execution would never reach the if inside the while.

As for a simpler way to write this:
```python
def create_counting_list(count_to_number):
    if count_to_number < 0:
        return 'cannot be negative'
    new_list = []
    count = 1
    while count <= count_to_number:
        new_list.append(count)
        count += 1
    return new_list
```
