### ISSUE TITLE
Re gists setup code

### ISSUE THREAD

**Issue by raghureddyram** [rmotr-curriculum/post-your-question-questions#81]
I'm not understanding this yield statement in relation to the db connection. I know yield acts as a generator normally, but I'm not sure what it does with the db connection. 

Also, why do you need to write db.close()? If this call is only supposed to clean the database, do you need to close the connection every time that you write a @pytest.fixture test?

**Assignment**: http://learn.rmotr.com/python/post-a-question/post-your/questions

**User code**:
```python
@pytest.fixture()
def clean_gists_database():
    db = sqlite3.connect(TESTING_DATABASE_PATH)
    with open(DATABASE_SCHEMA_PATH, 'r') as fp:
        db.executescript(fp.read())
    yield db
    db.close()
    os.remove(TESTING_DATABASE_PATH)
    
#In the exercise for interacting with the database and requests I saw this yield db statement. What does this do in practice? I saw that the db had to be manually closed as well. I thought there's a way to setup a context manager with a 'with something as db' statment. Do we always have to close the db connection? 
```

**Comment by jsymons** [comment]
So the way this fixture works is that any time a test uses it, it produces a cleaned version of the database. It kind of works like a context manager (where you use `with`). It first creates a new clean version of the database and then `yield`s it to the test. When the test is done running the statements after the yield are executed. We need to close the database because this entire function is called **every** time a test uses the fixture, it is not just being reused and passed between tests, we create a new clean database for **each** test.
